#!/usr/bin/env bash
#
# A custom git command that synchronizes with a remote that might have many submodule changes that require updating in
# order to successfully pull the latest changes from the remote. For example, when `git pull --recurse-submodules`
# fails with `Errors during submodule fetch:`, it may be because a submodule has been updated in such a way that it
# cannot be updated to the latest without being synchronized as well.
#
# Author: Lucas Magasweran <lrm@linux.com>
#
set -o xtrace

git pull --no-recurse-submodules
git submodule update --recursive
git submodule sync --recursive
git submodule update -f --init --recursive
git pull --recurse-submodules

exit 0
